login: &login
  adapter: postgresql
  host: localhost
  port: 5432
  username:
  password:

development:
  adapter: postgresql
  database: gameshow_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: gameshow_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: gameshow_production
  pool: 5
  timeout: 5000